mmorpg/mmorpg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.urls import path, include
from usersapp.views import IndexView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('posts/', include('usersapp.urls', namespace='userapp_old')),
    path('pages/', include('django.contrib.flatpages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mmorpg/usersapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    PostCreateView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
    UserLoginView,
    UserRegisterView,
    UserProfileView,
    EmailVereficationView,
    CommentCreateView,
    CommentListView,
    CommentDetailView,
    confirm_comment,
)


app_name = "usersapp"

urlpatterns = [
    path("", PostCreateView.as_view(), name="add_post"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post"),
    path("post/<int:pk>/update", PostUpdateView.as_view(), name="post_update"),
    path("post/<int:pk>/delete", PostDeleteView.as_view(), name="post_delete"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("profile/<int:pk>/", UserProfileView.as_view(), name="profile"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "verify/<str:email>/<uuid:code>/",
        EmailVereficationView.as_view(),
        name="email_verefication",
    ),
    path(
        "comments/<int:pk>/comment_create",
        CommentCreateView.as_view(),
        name="comment_create",
    ),
    path("comments/", CommentListView.as_view(), name="comments"),
    path("comment/<int:pk>/", CommentDetailView.as_view(), name="comment"),
    path("comment/<int:pk>/confrim", confirm_comment, name="confirm"),
]

mmorpg/usersapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.urls import reverse
from django.conf import settings
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to="users_images", blank=True, null=True)
    is_verified_email = models.BooleanField(default=False)
    email = models.EmailField(unique=True, blank=False)


class Category(models.Model):
    name = models.CharField(max_length=56, unique=True)

    def __str__(self) -> str:
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=150)
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    file_add = models.FileField(null=True, blank=True, upload_to="add_files")

    def __str__(self) -> str:
        return f"Объявление: {self.title} | Автор объявления: {self.author}"


class Comment(models.Model):
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.text[:30]


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f"EmailVerefication object for {self.user.email}"

    def send_verefication_email(self):
        link = reverse(
            "usersapp:email_verefication",
            kwargs={"email": self.user.email, "code": self.code},
        )
        verefication_link = f"{settings.DOMAIN_NAME}{link}"
        subject = f"Подтверждение учетной записи для {self.user.username}"
        message = (
            "Для подтверждения учетной записил для {} перейдите по ссылке {}".format(
                self.user.email, verefication_link
            )
        )
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

mmorpg/usersapp/forms.py
import uuid
from datetime import timedelta

# from typing import Any
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
)
from .models import User, EmailVerification, Comment
from django import forms
from django.utils.timezone import now


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control py-4",
                "placeholder": "Введите имя пользователя",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control py-4", "placeholder": "Введите пароль"}
        )
    )

    class Meta:
        model = User
        fields = ("username", "password")


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control py-4",
                "placeholder": "Введите имя пользователя",
            }
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control py-4",
                "placeholder": "Введите адрес эл. почты",
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control py-4", "placeholder": "Введите пароль"}
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control py-4", "placeholder": "Подтвердите пароль"}
        )
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit)
        expiration = now() + timedelta(hours=48)
        record = EmailVerification.objects.create(
            code=uuid.uuid4(), user=user, expiration=expiration
        )
        record.send_verefication_email()
        return user


class UserProfileForm(UserChangeForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4"})
    )
    email = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4", "readonly": True})
    )
    image = forms.ImageField(
        widget=forms.FileInput(attrs={"class": "custom-file-label"}), required=False
    )

    class Meta:
        model = User
        fields = ("username", "email", "image")


# class PostCreateForm(forms.ModelForm):
#     title = forms.CharField(widget=forms.TextInput(attrs={
#       'class': 'form-control py-4',
#       'placeholder': 'Введите заголовок'
#     }))
#     category = forms.ModelMultipleChoiceField(
#       queryset=Category.objects.all(), widget=forms.Select(attrs={
#           'class': 'form-control py-4', 'placeholder': 'Выберите категорию'
#       })
#     )
#     description = forms.CharField(widget=forms.TextInput(attrs={
#       'class': 'form-control py-4', 'placeholder': 'Введите описание'
#     }))

#     class Meta:
#         model = Post
#         fields = ('title', 'category', 'description')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

mmorpg/usersapp/views.py
# from typing import Any
# from django import http
# from django.db.models.query import QuerySet
# from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
# import datetime
from django.shortcuts import HttpResponseRedirect
from .models import Post, Comment, User, EmailVerification
from django.urls import reverse
from .forms import UserLoginForm, UserRegisterForm, UserProfileForm, CommentForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.views.generic import TemplateView, DetailView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.views import LoginView


class IndexView(TemplateView):
    template_name = "usersapp/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.all()
        context["title"] = "Главная страница"
        return context


class CommentListView(LoginRequiredMixin, ListView):
    model = Comment
    template_name = "usersapp/comments.html"
    context_object_name = "comments"

    def get_queryset(self):
        queryset = Comment.objects.filter(author=self.request.user)
        return queryset


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = "usersapp/comment_create.html"
    form_class = CommentForm
    context_object_name = "comment_create"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = User.objects.get(id=self.request.user.id)
        comment.post = Post.objects.get(id=self.kwargs.get("pk"))
        comment.save()

        comment = Comment.objects.get(id=comment.id)
        send_mail(
            subject="У вас новый отклик на объявление!",
            message=f"Здравствуйте, {comment.post.author}. На ваше объявление оставили отклик! Посмотреть отклик: http://127.0.0.1:8000/",
            from_email="sabi.raf@yandex.ru",
            recipient_list=[comment.post.author.email],
        )
        return HttpResponseRedirect(reverse("index"))


class CommentDetailView(DetailView):
    model = Comment
    template_name = "usersapp/comment.html"
    context_object_name = "comment"


@login_required
def confirm_comment(request, **kwargs):
    if request.user.is_authenticated:
        comment = Comment.objects.get(id=kwargs.get("pk"))
        comment.status = True
        comment.save()

        comment = Comment.objects.get(id=comment.id)
        send_mail(
            subject="Форум MMORPG: Ваш отклик принят!",
            message=f"Здравствуйте, {comment.author}, Автор объявления {comment.post.title} принял Ваш отклик! Зайдите в личный кабинет:http://127.0.0.1:8000/posts/comments",
            from_email="sabi.raf@yandex.ru",
            recipient_list=[
                comment.post.author.email,
            ],
        )
        return HttpResponseRedirect(reverse("index"))
    else:
        return HttpResponseRedirect("/posts/login")


# Post
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "usersapp/posts.html"
    # form_class = PostCreateForm
    fields = ("title", "category", "description", "file_add")
    # success_url = reverse_lazy('usersapp:profile')

    def get_success_url(self):
        self.success_url = reverse("index")
        return super().get_success_url()

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDetailView(DetailView):
    model = Post
    template_name = "usersapp/post.html"
    context_object_name = "post"


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = "usersapp/posts.html"
    fields = ("title", "category", "description")

    def get_success_url(self):
        self.success_url = reverse("index")
        return super().get_success_url()


class PostDeleteView(DeleteView):
    model = Post
    template_name = "usersapp/post_delete.html"
    context_object_name = "post_delete"

    def get_success_url(self):
        self.success_url = reverse("index")
        return super().get_success_url()


# User
class UserLoginView(LoginView):
    template_name = "usersapp/login.html"
    form_class = UserLoginForm


class UserRegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "usersapp/register.html"
    success_url = reverse_lazy("usersapp:login")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Регистрация"
        return context


class UserProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "usersapp/profile.html"

    def get_success_url(self):
        return reverse_lazy("usersapp:profile", args=(self.object.id,))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Личный кабинет"
        context["posts"] = Post.objects.filter(author=self.object)
        context["my_comments"] = Comment.objects.filter(author=self.object)
        return context


class EmailVereficationView(TemplateView):
    template_name = "usersapp/email_verefication.html"

    def get(self, request, *args, **kwargs):
        code = kwargs["code"]
        user = User.objects.get(email=kwargs["email"])
        email_verif = EmailVerification.objects.filter(user=user, code=code)
        if email_verif.exists() and not email_verif.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVereficationView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse("index"))

mmorpg/usersapp/templates/usersapp/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}{% endblock %}</title>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    {% block css %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex flex-wrap justify-content-center" id="navbarTogglerDemo01">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Главная страница</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'usersapp:add_post' %}">Создать объявление</a>
            </li>
            {% endif %}
            {% if not user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'usersapp:register' %}">Регистрация</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'usersapp:comments' %}">Все отклики</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'usersapp:profile' user.id%}">Личный кабинет</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'usersapp:logout' %}">Выйти</a>
            </li>
            {% else %}
            <li class="nav-item active ">
              <a class="nav-link " href="{% url 'usersapp:login' %}">Войти</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}
</body>
</html>


{% load static %}

mmorpg/usersapp/templates/usersapp/comment.html
{% extends 'usersapp/base.html' %}


{% block title %}
Подтвердить отклик
{% endblock %}

{% block content %}
<div class="card-body text-center my-4 card shadow-lg border-0 rounded-lg ">
    <h3>Вы собираетесь подтвердить отклик:</h3>
    <h6>{{ comment.created|date:'d.m.Y G:i' }}</h6>
    <p>{{ comment.text }}</p>
    <h6>Автор: {{ comment.author }}</h6>
    {% if user.is_authenticated %}
    {% if user.id != comment.post.author.id %}
    <div>
        <button><a href="{% url 'usersapp:confirm' comment.id %}">Подтвердить</a></button>
    </div>
    {% endif %}
    {% endif %}
    <hr>

    <h3>Объявление</h3>
    <h4>{{ comment.post.title }}</h4>
    <h6>Автор: {{ comment.post.author }}</h6>
    <h6>{{ comment.post.created|date:'d.m.Y G:i' }}</h6>
    <p>{{ comment.post.description }}</p>
    <!-- <p>{{ comment.post.author.email }}</p> -->
</div>
{% endblock %}

mmorpg/usersapp/templates/usersapp/comment_create.html
{% extends 'usersapp/base.html' %}



{% block title %}
    Оставьте отклик
{% endblock %}


{% block content %}
    <h3>Оставьте отклик</h3>
    <hr>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Откликнуться">
    </form>
{% endblock %}

mmorpg/usersapp/templates/usersapp/comments.html
{% extends 'usersapp/base.html' %}


{% block title %}
Мои отклики
{% endblock %}


{% block content %}
<h3>Все отклики</h3>
<hr>
{% if comments %}
{% for com in comments %}
<ul>
    <li>Объявление: {{ com.post.title }}</li>
    {{ comment.post.title }}
    <li>Текст: {{ com.text }}</li>
    <li>
        {% if com.status %}
        Подтвержден: Да
        {% else %}
        Подтвержден: Нет
        {% endif %}
    </li>
    <li>Дата создания: {{ com.post.created }}</li>
    <li>Откликнулся - <strong>{{ com.post.author }}</strong></li>
</ul>
{% endfor %}
{% else %}
<p>Откликов нет</p>
{% endif %}
{% endblock %}

mmorpg/usersapp/templates/usersapp/email_verefication.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Подтверждение электронной почты</title>
    <link href="../vendor/css/auth.css" rel="stylesheet"/>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>Ваша учетная запись успешно подтверждена!</h4>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'index' %}">Продолжить</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
</body>
</html>

mmorpg/usersapp/templates/usersapp/index.html
{% extends 'usersapp/base.html' %}
{% load static %}


{% block title %}
    {{ title }}
{% endblock %}


{% block content %}
    {% if posts %}
    <h1>Объявления</h1>
    <hr>
    {% for post in posts %}
    <div>{{ post }}
        <ul>
            <li><a href="{% url 'usersapp:post' post.id %}">{{ post.title }}</a></li>
            <li>Описание - {{ post.description }}</li>
            <li>Роль - {{ post.category }}</li>
            <!-- <li>Автор - {{ post.author }}</li> -->
        </ul>
    </div>
    {% endfor %}
    {% else %}
    <h1>Объявлений нет</h1>
    {% endif %}
{% endblock %}

mmorpg/usersapp/templates/usersapp/login.html
{% extends 'usersapp/base.html' %}
{% load static %}


{% block title %}
    Авторизация
{% endblock %}


{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or form.non_field_errors %}
                        <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                             {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                             {% else %}
                                {{ form.non_field_errors }}
                            {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'usersapp:login' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                        {{ form.password }}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>

                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'usersapp:register' %}">Зарегистироваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}

mmorpg/usersapp/templates/usersapp/post.html
{% extends 'usersapp/base.html' %}


{% block title %}
    Объявление
{% endblock title %}

{% block content %}
    <div class="card-body text-center my-4 card shadow-lg border-0 rounded-lg ">
        <h1 class="">{{ post.title }}</h1>
        <hr>
        <h5 class="my-4">Роль: {{ post.category }}</h5>
        <p class="my-4">Описание: {{ post.description }}</p>
        {% if user.is_authenticated and user != post.author %}
        <a href="{% url 'usersapp:comment_create' post.id %}">Откликнуться</a>
        {% endif %}
    </div>

{% endblock %}

mmorpg/usersapp/templates/usersapp/profile.html
{% extends 'usersapp/base.html' %}
{% load static %}



{% block title %}
{{ title }}
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12">
                <img width="100" height="100"
                    src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'users/img/default_avatar.jpg' %} {% endif %}"
                    class="img-thumbnail">
            </div>
            <form action="{% url 'usersapp:profile' user.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-8">
                        <div class="form-group">
                            <label class="small mb-3" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-8">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label mt-3" for="{{ form.image.id_for_label }}">Выберите
                                изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-8">
                        <label class="small mb-3" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
            <h4 class="mt-3 mb-3 text-center">
                Мои объявления
            </h4>
            {% for post in posts %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.description }}</p>
                    <p>Количество откликов: 5</p>
                    <li><a href="{% url 'usersapp:post_update' post.id %}">Редактировать</a></li>
                    <li><a href="{% url 'usersapp:post_delete' post.id %}">Удалить</a></li>
                </div>
            </div>
            {% endfor %}
            <hr>
            <h4 class="mt-3 mb-3 text-center">Мои отклики на объявления</h4>

            {% for comment in my_comments %}
            <div class="card mb-3">
                <div class="card-body">

                    <h5><a href="{% url 'usersapp:post' comment.post.id %}">{{ comment.post.title }}</a></h5>
                    <p>Автор: {{ comment.post.author }}</p>
                    <h5>Мой отклик:</h5>
                    {{ comment.text }}
                    <p>{{ comment.created }}</p>
                    <!--p>{{ comment.status }}</!--p-->
                    {% if not comment.status %}
                    <a href="{% url 'usersapp:comment' comment.id %}">Подтвердить</a>
                    {% else %}
                    <p>Принято</p>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mmorpg/usersapp/templates/usersapp/register.html
{% extends 'usersapp/base.html' %}
{% load static %}


{% block title %}
    {{ title }}
{% endblock %}


{% block content %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}

                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'usersapp:register' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                                почты</label>
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                                    пароля</label>
                                                    {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'usersapp:login' %}">Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}